import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import arStyles from '../styles/Ar.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>First Ar app</h1>
        <body className={arStyles.arbody}>
          {/* minimal loader shown until image descriptors are loaded */}
          <div className={arStyles.arjsloader}>
            <div>Loading, please wait...</div>
          </div>
          <a-scene
            vr-mode-ui="enabled: false;"
            renderer="logarithmicDepthBuffer: true;"
            embedded
            arjs="trackingMethod: best; sourceType: webcam;debugUIEnabled: false;"
          >
            {/* <!-- we use cors proxy to avoid cross-origin problems ATTENTION! you need to set up your server --> */}
            <a-nft
              type="nft"
              url="your-server/https://raw.githack.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex/trex-image/trex"
              smooth="true"
              smoothCount="10"
              smoothTolerance=".01"
              smoothThreshold="5"
            >
              <a-entity
                gltf-model="your-server/https://raw.githack.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex/scene.gltf"
                scale="5 5 5"
                position="50 150 0"
              >
              </a-entity>
            </a-nft>
            <a-entity camera></a-entity>
          </a-scene>
        </body>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
